apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sofienech/client:8
        ports:
        - containerPort: 80
